version: '3.4'

services:
  frontend-client:
    build: .
    image: docker.medzdrav.ru/rgs-frontend-client:dev
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - 3001:3000
    restart: always